apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coverfly-ingress
  namespace: coverfly
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: coverfly.local
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-gateway
                port:
                  number: 4000

